apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: entandoplugins.entando.org
spec:
  group: entando.org
  version: v1
  additionalPrinterColumns:
    - name: Phase
      type: string
      JSONPath: .entandoStatus.entandoDeploymentPhase
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
    - name: Host
      type: string
      JSONPath: .spec.ingressHostName
    - name: Path
      type: string
      JSONPath: .spec.increatePath
    - name: Image
      type: string
      JSONPath: .spec.image
    - name: DBMS
      type: string
      JSONPath: .spec.dbms
    - name: Replicas
      type: integer
      JSONPath: .spec.replicas
  names:
    kind: EntandoPlugin
    plural: entandoplugins
    shortNames:
      - eplugs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            ingressHostName:
              type: string
              pattern: '^([A-Za-z0-9-]{1,63}\.)+[[A-Za-z0-9-]{1,63}$'
            tlsSecretName:
              type: string
              pattern: '^([a-z])+([a-z0-9-\.])*[a-z0-9]$'
            replicas:
              type: integer
              minimum: 1
              maximum: 10
            image:
              type: string
            ingressPath:
              type: string
            healthCheckPath:
              type: string
            keycloakSecretToUse:
              type: string
              pattern: '^([a-z])+([a-z0-9-\.])*[a-z0-9]$'
            clusterInfrastructureToUse:
              type: string
              pattern: '^([a-z])+([a-z0-9-\.])*[a-z0-9]$'
            dbms:
              type: string
              pattern: '^(mysql|oracle|postgresql|none)?$'
            securityLevel:
              type: string
            parameters:
              type: object
            connectionConfigNames:
              type: array
              items:
                type: string
            companionContainers:
              type: array
              items:
                type: string
            roles:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: string
                  name:
                    type: string
            permissions:
              type: array
              items:
                type: object
                properties:
                  clientId:
                    type: string
                  role:
                    type: string
        entandoStatus: {}
