#TODO get the ENUMS working and come up with a good RegExp pattern for registry.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: entandokeycloakservers.entando.org
spec:
  group: entando.org
  version: v1
  additionalPrinterColumns:
    - name: Phase
      type: string
      JSONPath: .entandoStatus.entandoDeploymentPhase
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
    - name: Host
      type: string
      JSONPath: .spec.ingressHostName
    - name: Image
      type: string
      JSONPath: .spec.imageName
    - name: DBMS
      type: string
      JSONPath: .spec.dbms
    - name: Replicas
      type: integer
      JSONPath: .spec.replicas
  names:
    kind: EntandoKeycloakServer
    plural: entandokeycloakservers
    shortNames:
      - ekcs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            imageName:
              type: string
            dbms:
              type: string
              pattern: '^(mysql|oracle|postgresql|none)$'
            tlsSecretName:
              type: string
              pattern: '^([a-z])+([a-z0-9-\.])*[a-z0-9]$'
            ingressHostName:
              type: string
              pattern: '^([A-Za-z0-9-]{1,63}\.)+[[A-Za-z0-9-]{1,63}$'
            entandoImageVersion:
              type: string
            replicas:
              type: integer
              minimum: 1
              maximum: 10
            parameters: {}
        entandoStatus: {}

