== Hello World for a Widget Using the App builder
:toc:

This tutorial will take you through the basics of creating an Entando widget and getting something it the page. This will also take you
through the basics of fragments which are re-usable pieces of UX.

=== Simple Widget Tutorial

For the hello world of custom widgets you can use the app builder to do
everything that you need to get your widgets on a page. In a production
system or a larger development environment you might build and
deploy these differently but this will give you a quick idea of the building blocks.

1. In the App Builder menu on the top go to UX Patterns --> Widgets
2. Select New
3. The Custom UI Field  is a freemarker template where you can put raw html and include freemarker logic
** You can import javascript, css, or anything you can do in normal HTML.
** For example, put <h2>Hello World</h2> in your widget, give it a name, and save it
4. Go to Page Designer --> Page Settings
5. In the Home Page dropdown select Home / Service and select save
6. Now we can put the widget on the page
7. Go to Page Designer --> Page Tree
8. On the row that says Service on the far right side select the Kebab button and select Configure
9. Now find the widget you created in step 4 on the right hand side
10. Drag and drop that onto the open frame on the page
11. Select Publish at the bottom of the screen
12. Then select Go to Homepage in the upper right
13. You should see "Hello World" on the page

=== Simple Fragment tutorial
A fragment is a way to take a common piece of front end code and reuse it across many
different pages or widgets. Elements that are common including basic html, javascript, or freemarker logic
can be stored as fragments and referenced via the `<@wp.fragment ...` tag.

Starting from the simple widget tutorial above:

1. In the app builder go to UX Patterns --> Fragments
2. Enter the code for the fragment as `test`
3. In the `Gui Code` enter `<h2>This is a fragment</h2>`
4. Now lets place the fragment on a page
5. Go to Ux Patterns --> Page models
6. On the row for `service` select edit
7. Use the fragment tag to place the fragment on the page `<@wp.fragment code="test"/>`
8. Save the page model
9. Go to homepage (assuming you've set the service page to the homepage)
10. You'll note that the fragment is printed including the HTML tags. By default html embedded via a fragment tag is escaped so you get
it rendered exactly as you enter it. You'll need to un-escape it to get it to render correctly.
11. Go back to your page model (UX Patterns --> Page Models) select service and edit
12. Change the tag to: `<@wp.fragment code="test" escapeXml=false/>`
13. Go back to the homepage
14. See your correctly rendered fragment

=== Freemarker Basics in Entando
The freemarker templating language gives you a lot of flexibility and power in how your pages are rendered.
You can include conditional logic, inject information from the backend, check for query parameters, and route to different pages.

For example, to check for a query parameter you can used
`<#if RequestParameters.myParam?exists > ...`

To check the current username
`<#if (Session.currentUser.username != "guest") >`

When you need dynamic behavior in your widgets consider using the power of freemarker.

== Useful Links
https://freemarker.apache.org/
