[id='current-release-notes']
:sectnums:
:imagesdir: images/

= 5.1.0 RELEASE NOTES

== NEW CAPABILITIES AND FEATURES
=== DOCUMENTATION AND DEPLOYMENT
* New OpenShift templates and documentation including a new getting started experience to deploy Entando applications on OpenShift
** See: http://docs.entando.com/#entando-on-openshift
* New examples, documentation, and templates to deploy Entando applications and AWS, Azure, and Google Cloud Engine using Kubernetes
** See: http://docs.entando.com/#_cloud_deployments_on_aws_azure_and_gce
* Added documentation and examples for deploying using an Oracle database

=== CONTENT MANAGEMENT
* The Entando CMS now gives the content editor the ability to crop, flip, and generally interact with an image uploaded to the application. This includes the ability to define pre-built crop ratios that are available to image editors
* The digital assets section of the CMS now allows for multiple images or attachments to be uploaded concurrently
* Metadata attached to images can now be stored attached to an image and that metadata can be used to
 automatically populate attributes defined in content types. For example, a description metadata tag on an image can be used to
 populate a caption or text in the content
 * The Entando CMS now supports the manual upload of very large files via digital
 assets. The files are loaded in chunks using base 64
 * The Entando CMS now allows for configuration to exclude content by id and
 by type from versioning plugin. Generally useful when high volume content
 delivered by API is generating large numbers of history records.
 * For updated CMS documentation and how to use the new features see:
 ** http://docs.entando.com/#_content_management_system
=== DIGITAL EXCHANGE
 The release of Entando 5.1.0 includes the tech preview release of the Entando Digital Exchange which is a new model for distributing and installing Entando components. This release includes the ability to install and manage all of the UI elements of an Entando application. Follow our blog and YouTube channels for more to come on the Digital Exchange.
 For documentation and getting started see:
 http://docs.entando.com/#_digital_exchange

=== APIs AND ENDPOINTS
 * Added new PATCH API capability to merge changes to page settings endpoints and established the framework for applying a PATCH in a custom API
 * Added the refresh token flow for OAuth and implemented token refresh in the App Builder
 * Added JSON REST APIs for content models and content types

=== FIXES AND UPDATES
* Resolved an issue where joinGroups weren’t updating on PUT calls
* Resolved an issue in App Builder where in some cases the locale of the App
Builder was lost on a refresh
* Updated processing around category creation when creating a new category
during the content creation workflow
* Updated errors in the Inspinia and PAM page models included in the PAM
template
* Resolved an issue where datatype date attributes were not returned correctly
in the app builder and updated data type actions in app builder
* Resolved an issue where page model titles were not displayed correctly in some
cases
* Resolved an issue in the CMS where the action button could become replicated
* Resolved issues related to moving page nodes in the App Builder
* General locale and translation updates for App Builder in Italian
* Resolved CMS image category and search issues related to category join groups
* Updated file download flow in the CMS to correctly download files on all
browsers
* Updated scripts and builds to resolve issues in Windows

=== NEW CAPABILITIES IN INTEGRATION WITH RED HAT PAM
* Added a new widget to display task details related to a selected task in Red Hat PAM. See PAM Process Task Detail widget in the app
* Added a new widget to allow a task form to be displayed independently on a page (the modal dialog functionality is unchanged.) See PAM-Task Form by DataType
* Added significant new configuration options to the PAM Datatable task list widget including
** Added configurable ability to claim a task directly from the task list
** Added configurable ability to open a new page with task details when clicking on a row in the task list
** Added the ability to include task variables as columns in the task list
Added the ability to disable the complete button in the task list
* Added process diagram widget to Inspinia BPM default widgets
* Updated case comment

=== CHANGES AND UPDATES IN 5.1.0 IN INTEGRATION WITH RED HAT PAM
* Resolved an issue viewing the SVG for the process diagram based on browser updates
* Resolved an issue where task details wouldn’t populate in some forms
* Updated integration with PAM based on integration with additional process and task configurations in customer test cases
* Updated task buttons to be fixed on the left hand side of task table
* Resolved an issue rendering and selecting checkbox values in forms
* Updated and resolved issues in form submission process for complex forms
* Various updates to task list to support integration with additional PAM field types
* Fixed round tripping for null values in forms and checkboxes

=== KNOWN ISSUES
* There is a known issue rendering the case comments widget independently. A patch will be provided to resolve this issue.
* On AWS and Azure there is a library missing to run the demo on Wildfly. A patch will be provided to resolve this issue.
* The process list widget will not render against PAM in some process definitions. To be patched in 5.1.1


=== SOFTWARE REQUIREMENTS
* Java 1.8
* npm 5.6.0+ (for ReactJS front ends)
* Maven 3.0.5+
* Ant 1.8.0+

=== LEGAL NOTICE
* LGPL v2.1 License for the Core
* MIT License for the components

=== LINKS AND RESOURCES
* Explore the code on GitHub: https://github.com/entando
* See our Getting Started guide: http://docs.entando.com/#getting-started
* See our Custom App Building guide: http://docs.entando.com/#_custom_app_building_with_entando
* Contribute to the software: https://central.entando.com/en/community.page
