[id='current-release-notes']
:sectnums:
:imagesdir: images/

= ENTANDO 6.0.0 RELEASE NOTES

== NEW CAPABILITIES AND FEATURES

=== GOAL OF E6

The goal of Entando 6 is to bring leading edge tools and architectures like micro frontends and Spring Boot to help developers build web applications that are truly modern. Entando 6 is Kubernetes-native and provides additional capabilities and functionalities to accelerate development, allow dynamic deployment, and simplify the life of the enterprise in Kubernetes. Entando 6 also provides blueprints to allow rapid development of applications and widgets using modern JS Frameworks.

=== ABOUT E6

Entando is the leading open source UX Innovation Platform that provides a modern development stack  for building cloud-native applications, allowing enterprises to rapidly innovate and develop exceptional user experiences.

=== WHAT'S NEW IN E6

=== Improved Developer Experience
One of the main objectives of Entando 6 is to modernize and update the toolkit available to developers working on an Entando application. With this release the Entando platform provides an entirely updated developer experience focusing on modern tools and architecture like kubernetes, microservices, modern JS frameworks, and many other standard toolkits.

==== Microservice Integration
** Build and deploy Entando plugins using microservices
*** Any application packaged as a container can be integrated and deployed alongside your Entando application
* Tools, examples, and new features using SpringBoot

==== Micro Frontends as Foundation for UX Development
* Microservices for the Frontend
** Develop self-contained, decoupled frontend UIs that can be managed and deployed as containerized bundles
** Works with any modern JS framework that supports Custom Elements
** Communicate between widgets supported via custom events
* Compose micro frontends into a user facing application using Entando
** Built on Custom Elements from Web Component specifications
** Inherit configuration, microservice, and identity management from Entando
* Backed by domain or use-case specific microservices

==== The Entando Blueprint
The Entando Blueprint is an extension of the JHipster microservices generation framework. The Entando Blueprint will automatically generate a Spring Boot microservice that is ready to be run as an Entando plugin including  micro-frontends, packaging, apis and other features needed to develop a ready to run web applications.

* Provides tools to automatically generate a complete web app ready to run as a service
** With defaults generated from an Entando JHipster blueprint
** Widgets, APIs, security, and runnable microservices that can be deployed and integrated with the Entando Kubernetes infrastructures
* Automatically generate micro-frontends for every entity added to your JHipster service
* Generated plugins installable in Digital Exchange

==== Updates to Infrastructure
The Entando Kubernetes infrastructure allows for the automated management of the plugin lifecycle via the Digital Exchange and the app builder.

* Kubernetes (operator, sidecar, ingress) for automated integration, deployment, and DevOps lifecycles
* Entando Kubernetes operator
** Automated integration and installation of plugins, micro frontends, and microservices
** Out of the box integration with Micro App Engine and microservices
** Enables Digital Exchange to install full stack applications
* First class support on OpenShift - supports OpenShift 3.11 and 4


==== Plugins as a Service
With Entando 6 the developer experience is focused on the development of plugins that run as microservices. An Entando plugin also has the ability to package and expose user experience in the form of micro frontends.

* Update Entando plugin architecture to be driven by microservices
* Plugins run as standalone microservices and take advantage of the APIs exposed by the Entando core to integrate with the Entando infrastructure
* Integrated via Entando Kubernetes infrastructure (operator, sidecar, ingress)
* Micro frontends (aka widgets) automatically registered and available for use
* New code generation and templating features
* Keycloak for identity management and security

==== All New Identity Management
* Keycloak as foundation for API security for both internal and external calls
* Users and roles in Keycloak used between services and end user identity management
* Entando automatically creates roles and permissions when creating a new Plugin as a Service and enables plugins to access those roles
* Supports standard protocols (OpenID Connect, OAuth 2.0 and SAML 2.0)


==== Progressive Web Apps
The Entando progressive web app architecture allows developers to take advantage of the Entando CMS APIs to easily drive content to a progressive web app. Entando also provides a React-based progressive web app application that can be used to bootstrap progressive web app development integrated with the Entando infrastructure.

* Drive content on mobile devices by using the Entando progressive web app architecture using the Entando CMS APIs
* Extends and utilizes Entando APIs and authentication

==== Improved App Builder
* CMS now a part of the app builder
* Updated digital exchange UI
* Extend the app builder by creating an App Builder app. The App Builder exposes build time hooks to add rich user experience to the Entando App Builder to support customer specific requirements
* Add widget configuration

==== Known Issues

* Some of the documentation is out of date relative to Entando 6 and will be incrementally updated to reflect new processes and tools
* At release the Entando CMS will be disabled in the App Builder at release
** The CMS will be added in a subsequent patch release (ETA week of Nov. 14)
* The CMS widgets to render content through the page model will not be available at release
* The CMS widgets will be added in a subsequent patch release (ETA week of Nov. 14)
*Plugins that require a configuration screen will need to manually enable the Integrations section and provide a micro-frontend to render that configuration


=== SOFTWARE REQUIREMENTS
* Java 1.8 or later required
* npm 5.6.0+ (for ReactJS front ends and blueprint execution)
* node LTS (for blueprint execution)
* Kubernetes environment required to run infrastructure or production code

=== LEGAL NOTICE
* LGPL v2.1 License for the Core
* MIT License for the components

=== LINKS AND RESOURCES
* Explore the code on GitHub: https://github.com/entando
* See our Getting Started guide: http://docs.entando.com/#getting-started
* See our Custom App Building guide: http://docs.entando.com/#_custom_app_building_with_entando
* Contribute to the software: https://central.entando.com/en/community.page
