[id='legacy-release-notes']
:sectnums:
:imagesdir: images/


= LEGACY ENTANDO RELEASE NOTES

== ENTANDO 5.0.1 RELEASE NOTES 

== ABSTRACT
This document contains release notes for Entando 5.0.1.

== CHANGES IN 5.0.1
*Library and dependency updates*

* We have updated the following as part of a general review of dependencies and updates based on Sonar scans: +
+
|===
| *Dependency* | *Updated to*
| Apache taglibs | 1.2.3
| commons-bean-utils | 1.9.2
| commons-io | 2.6
| CXF | 3.1.16
| Freemarker | 2.3.36-incubating
| Junit | 4.8.2
| log4j | 2.10.0
| Spring | 5.0.8.RELEASE
| Spring Security (new) | 5.0.7.RELEASE
| Struts2 | 2.5.17
| Struts2-jquery | 4.0.3
|===

*Security updates*

* The dependency version updates above include changes based on Sonar OWASP dependency scans

*Swagger*

* This release includes the addition of Swagger API documentation on top of the existing Entando REST endpoints
* Entando applications can extend Entando APIs and configure endpoints to be exposed via Swagger
* Learn more here: http://docs.entando.com/#_configuring_swagger_optional

*REST API Definition*

* Resolved a bug that prevented custom package scans from exposing endpoints in Entando REST endpoints
* Learn more about exposing REST endpoints in an Entando application: http://docs.entando.com/#_building_a_rest_api

*Red Hat Process Automation Manager (PAM) plugin*

* Added a new page model to integrate and display all of the Entando case management widgets on a single page
* Added support for new field types:
** Check boxes
** Radio buttons
** List boxes
** Text areas
** Dates
* Available to be added to projects as a Maven dependency
* Resolved error condition when connecting to PAM 7.1 instances
* Updated _Form by Datatype_ widget to support additional fields and resolved issues related to rendering forms for different models
* Resolved issues related to rendering PAM widgets and pages

*Authentication and Authorization Model*

* The release in Entando 5.0.1 includes a change in authentication models from OLTU to Spring Security
* Entando endpoints and user management are all now integrated with Spring security

=== Defect Resolution and General Updates

*App Builder*

* Resolved issue displaying and selecting join groups
* Resolved page title display
* Resolved label issue in data type and data model
* Resolved issue related to the display of groups for widget types, content, and resources
* Resolved username and email display issue in User Management
* Resolved issue moving nodes in page tree
* Added the ability to save an empty user profile
* Added warning about deleting locked Fragments
* Updated display of file and folder size in File Browser
* Updated validation rules for username and password to match API requirements
* Updated validation rules for page model and page naming to match API requirements

*CMS*

* Resolved issue with duplicated column names
* Resolved issues editing content after adding a join group
* Resolved breadcrumb display issue
* Resolved edge condition in content preview actions
* Resolved various issues surrounding the addition of attachments to content
* Resolved issues in the addition and management of categories

== Tech Preview

=== Known Issues

Some dependencies in 5.0.1 still reference snapshot versions of components and other related products. This will be resolved in 5.0.2.

*Versioning Information*

.Jars and artifacts included in this release:
|===
| *Artifact* | *Version*
| entando-core | 5.0.1
| entando-archetypes | 5.0.1
| entando-ux-packages | 5.0.1
| entando-components  | 5.0.1
| app-builder | 5.0.1
|===

=== Software Requirements

* Java 1.8+
* npm 5.6.0+ (for ReactJS front ends)
* Maven 3.0.5+
* Ant 1.8.0+

=== Legal Notice

* LGPL v2.1 license for the Entando core
* MIT license for the components


=== Links and Resources

* Explore the code on GitHub: https://github.com/entando
* See our Getting Started guide: http://docs.entando.com/#getting-started
* See our Custom App Building guide: http://docs.entando.com/#_custom_app_building_with_entando
* Contribute to the software: https://central.apps.entando.com/en/community.page



== ENTANDO 5.0.0 RELEASE NOTES

== ABSTRACT
This document contains release notes for Entando 5.0.

== PREFACE
These release notes highlight new features in Entando 5.0, list features that are in technical preview, and include any known issues.

== GOAL OF ENTANDO 5
The goal of Entando 5.0 is to fully engage our platform with the Modern Applications revolution by designing for a cloud-based infrastructure, adapting our architecture to be more distributed, and fully supporting DevOps methodologies.

== ABOUT ENTANDO 5
Entando 5 represents a fundamental update to the Entando infrastructure to support modern application development processes including: new options for clustering, cloud native deployment, out of the box support for deploying apps in OpenShift, new UI technologies, and an updated widget development process.

These release notes provide a technical introduction to the changes included in Entando 5. Check out our Installation guide, Getting Started guide, or our blog for examples and more on putting Entando 5 to work.

== WHAT'S NEW WITH ENTANDO 5
* Infrastructure/Platform
** Hybrid hosting environment
*** Entando 5 supports deployment in both public and private cloud configurations including deployment using Docker and OpenShift
** Cloud native clustering using a JSR 107 compliant cache for scaling in the cloud
*** Entando 5 introduces the ability to back an installation of the MApp Engine-engine with a JSR 107 cache for multinode high availability (HA) configuration
*** A reference implementation using Infinispan is provided in the entando-components project
** Container deployment
*** Deploy directly to OpenShift using images published to the Red Hat catalog
*** Deploy using Docker images provided on DockerHub
*** Install an Entando project using provided Source to Image (S2I) Docker images
** New public facing REST APIs
*** Entando 5 exposes a new set of REST APIs for interacting with App Builder assets
** Decoupled application builder and micro engine for updated deployment options
*** This release decouples the application builder's front end from the Entando engine allowing the engine and App Builder to be deployed separately. The updated application builder is a ReactJS based application that uses REST APIs and can be deployed and managed separately from the MApp Engine
** Upgrade to Spring 5
** Security updates
We have performed security scans as part of the Entando 5 software release to ensure that we are using secure libraries and practicing secure coding practices within our application. We continue to use automated tools and manual security reviews to monitor and evaluate the security of the Entando platform. Notable updates include:
*** Various library version upgrades to match OWASP security scan results at time of release
*** Software updates to support SonarQube security scans and improve software security

*** The Entando core has been updated to Spring 5.0.5
* Processes
** Supports DevOps processes
*** First class support for deploying Entando projects on Docker and OpenShift
*** New archetypes to deploy to OpenShift and Docker using Fabric8
*** Created Docker base images for quick extension and deployment
** Manage full CI/CD life cycle
*** Created reference implementation of Entando Docker images in Jenkins to create, deploy, and manage an application built using Entando in a CI/CD environment
** Decoupled CMS from MApp Engine
*** The CMS capability available in Entando 4.3.2 has been decoupled from the core MApp Engine implementation and will be available as a plugin to Entando 5 in a future release
** New component development experience
*** The Entando Component Generator (formerly edo) has been updated to use a configuration file to more easily select different types of components to generate

=== KNOWN ISSUES
* The ability to associate attributes with User Profiles is not implemented in the decoupled App Builder
** Workaround: use the legacy application screens to add attributes to user profiles
** Anticipated fix in first patch release
* Manually editing and saving Data Types and Data Models in the decoupled App Builder has errors
** Workaround: use the legacy application screens to edit Data Types
** Anticipated fix in future patch release
* If you move the homepage to a child of itself in the page tree it can result in browser and application stability problems
* Anticipated fix in future patch release
** The PAM Datatable and Task List widgets only function in the legacy App Builder

=== VERSIONING INFORMATION

.Jars and artifacts included in this release:
|===
|Artifact |Version

|entando-core
|5.0.0

|entando-archetypes
|5.0.0

|entando-ux-packages
|5.0.0

|entando-vfs-manager
|5.0.0

|app-builder
|5.0.0

|MApp-Engine-admin
|5.0.0
|===


=== SOFTWARE REQUIREMENTS
* Java 1.8+
* npm 5.6.0+ (for ReactJS front ends)
* Maven 3.0.5+
* Ant 1.8.0+

=== LEGAL NOTICE
* LGPL v2.1 License for the Core
* MIT License for the components



=== LINKS AND RESOURCES
* Explore the code on GitHub: https://github.com/entando
* See our Getting Started guide: http://docs.entando.com/#getting-started
* See our Custom App Building guide: http://docs.entando.com/#_custom_app_building_with_entando
* Contribute to the software: https://central.entando.com/en/community.page
