[id='release-notes-5.0.0']

= Entando 5.0.0 Release Notes

== Abstract
This document contains release notes for Entando 5.0.

== Preface
These release notes highlight new features in Entando 5.0, list features that are in technical preview, and include any known issues.

== Goal of Entando 5
The goal of Entando 5.0 is to fully engage our platform with the Modern Applications revolution by designing for a cloud-based infrastructure, adapting our architecture to be more distributed, and fully supporting DevOps methodologies.

== About Entando 5
Entando 5 represents a fundamental update to the Entando infrastructure to support modern application development processes including: new options for clustering, cloud native deployment, out of the box support for deploying apps in OpenShift, new UI technologies, and an updated widget development process.

These release notes provide a technical introduction to the changes included in Entando 5. Check out our Installation guide, Getting Started guide, or our blog for examples and more on putting Entando 5 to work.

== What's New with Entando 5
* Infrastructure
** Hybrid hosting environment
*** Entando 5 supports deployment in both public and private cloud configurations including deployment using Docker and OpenShift
** Cloud native clustering using a JSR 107 compliant cache for scaling in the cloud
*** Entando 5 introduces the ability to back an installation of the micro-engine with a JSR 107 cache for multi node HA configuration
*** A reference implementation using Infinispan is provided in the entando-components project
** Container deployment
*** Deploy directly to OpenShift using images published to LINK
*** Deploy using Docker images provided on DockerHub
*** Install an Entando project using provided Source to Image (S2I) Docker images
** New public facing REST APIs
*** Entando 5 exposes a new set of REST APIs for interacting with app builder assets
*** The API documentation is in the Swagger documentation deployed with every application created using an Entando archetype
** Virtual file system (VFS)
*** Entando 5 introduces an optional virtual file system (VFS) for managing and deploying assets created in the Entando App Builder. Employing the VFS pushes artifacts generated by Entando to a Git repository. Then once the assets are on Git they can be deployed to other Entando micro-engine instances via a CI/CD pipeline of your choice
*** The VFS uses the public REST APIs to fetch and deploy assets to Git
** Decoupled application builder and micro engine for updated deployment options
*** This release decouples the application builder's front end from the Entando engine allowing the engine and app builder to be deployed separately. The updated application builder is a ReactJS based application that uses REST APIs and can be deployed and managed separately from the micro-engine
** Upgrade to Spring 5
*** The Entando core has been updated to Spring 5.0.5
* Processes
** Supports DevOps processes
*** First class support for deploying Entando projects on Docker and OpenShift
*** New archetypes to deploy to OpenShift and Docker using Fabric8
*** Created docker base images for quick extension and deployment
** Manage full CI/CD life cycle
*** Created reference implementation of Entando Docker images in Jenkins to create, deploy, and manage an application built using Entando in a CI/CD environment
** Decoupled CMS from micro-engine
*** The CMS capability available in Entando 4.3.2 has been decoupled from the core micro-engine implementation and will be available as a plugin to Entando 5 in a future release
** New component development experience
*** The Entando Component Generator (formerly edo) has been updated to use a configuration file to more easily select different types of components to generate
* Security updates
We have performed security scans as part of the Entando 5 software release to ensure that we are using secure libraries and practicing secure coding practices within our application. We continue to use automated tools and manual security reviews to monitor and evaluate the security of the Entando platform. Notable updates include:
** Various library version upgrades to match OWASP security scan results at time of release
** Software updates to support SonarQube security scans and improve software security

=== Known Issues

=== Versioning Information

.Jars and artifacts included in this release:
|===
|Artifact |Version

|entando-core
|5.0.0

|entando-archetypes
|5.0.0

|entando-ux-packages
|5.0.0

|entando-vfs-manager
|5.0.0

|app-builder
|5.0.0

|micro-engine-admin
|5.0.0
|===


=== Software requirements
* Java 1.8+
* npm 5.6.0+ (for ReactJS front ends)
* Maven 3.0.5+
* Ant 1.8.0+

=== Legal notice
* LGPL v2.1 License for the Core
* MIT License for the components



=== Links and resources
* Explore the code on GitHub: https://github.com/entando
* Check out Getting Started experience
* Contribute to the software
