[id='installation']
:sectnums:
:imagesdir: images/

= INSTALLING ENTANDO ENTANDO 6

== PREREQUISITES
=== SPACE AND HARDWARE REQUIREMENTS
Entando is a built to be a very light framework requiring limited runtime resources. When extending Entando in a development setting, sizing for development environments that add to an Entando install is up to individual user requirements.

=== INSTALLED PREREQUISITES:
* Java 1.8+
* npm 5.6.0+
* Maven 3.0.5+
* Ant 1.8.0+
* Git
* A kubernetes environment. (OpenShift 3.11 or 4.x or kubernetes 1.14+)

== PREPARATION

1. Determine routing suffix of your kubernetes instance
2. Determine the docker registry to use. By default the Entando infrastructure will use docker.io
3. Establish if you can get a K8S cluster admin role for the controllers
4. Download these files for installation

* link:https://dev.entando.org/resources/crds.zip[CRDS]
* link:https://dev.entando.org/resources/custom_resources_yamls.zip[Custom Resource Yamls]

== INTRODUCTION
Many of the services and containers deployed in an Entando 6 instance are meant to be deployed once and be shared
as cluster level infrastructure. For getting started purposes you can deploy everything in the same namespace if preferred. The instructions
below walk you through deploying the cluster level infrastructure separately so that you only have to do that deployment once. Then you can
simply create new Entando Apps in their own namespace for future deployments.

== STEPS WITH A CLUSTER ADMIN ROLE

. Create entando-controllers namespace

*OpenShift*
----
oc new-project entando-controllers
----

*Kubernetes*
----
kubectl create namespace entando-controllers
----
[start=2]
. Assign the cluster-admin cluster role to the entando-controllers default service account

*OpenShift*
----
oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:entando-controllers:default
----

*Kubernetes*
----
kubectl create clusterrolebinding entando-controllers --clusterrole=cluster-admin --serviceaccount=entando-controllers:default
----

[start=3]
. Modify the operator.yaml file to reflect the two variables and modify the yaml accordingly

* ENTANDO_DEFAULT_ROUTING_SUFFIX
* ENTANDO_K8S_OPERATOR_REGISTRY

----
If you're using a local minikube instance, as value for ENTANDO_DEFAULT_ROUTING_SUFFIX use your minikube ip (or microk8s ip) + `.nip.io` suffix. With minikube, this command should return what you need echo "$(minikube ip).nip.io"
----

[start=4]
. Create the operator deployment.

[NOTE]
There's a small difference between OpenShift and Kubernetes supported versions for this. The provided file works out-of-the box for OpenShift, but in order to use it with Kubernetes you need to change the version to use `apps/v1`

*OpenShift*
----
oc create -f operator.yaml -n entando-controllers
----

*Kubernetes*
----
kubectl create -f operator.yaml -n entando-controllers
----

[start=5]
. Setup keycloak
.. If you're using an external-keycloak instance.

Create external keycloak secret after updating the yaml file with the keycloak admin credentials

*OpenShift*
----
oc create -f keycloak-secret.yaml -n entando-controllers
----

*Kubernetes*
----
kubectl create -f keycloak-secret.yaml -n entando-controllers
----

.. If you need to create a local keycloak instance

Create a keycloak project

*OpenShift*
----
oc new-project keycloak-namespace
----

*Kubernetes*
----
kubectl create namespace keycloak-namespace
----

Create the keycloak resource

*OpenShift*
----
oc create -f keycloak-server.yaml -n keycloak-namespace
----

*Kubernetes*
----
kubectl create -f keycloak-server.yaml -n keycloak-namespace
----

Make sure the `keycloak-admin-secret` has been created in the entando-controllers namespace. If not, something went wrong during keycloak installation and you need to reinstall it

[start=6]
. Create Entando Cluster infrastructure (Digital Exchange, UserManagement and EntandoK8SService)

*OpenShift*
----
# Create the project
oc new-project entando-infra-namespace

# Add the cluster-admin role to the default service account on entando-infra-namespace, required for k8s-service
oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:entando-infra-namespace:default

# Create the resource from the file
oc create -f entando-infra.yaml -n entando-infra-namespace
----

*Kubernetes*
----
# Create the namespace
kubectl create namespace entando-infra-namespace

# Add the cluster-admin role to the default service account on entando-infra-namespace, required for k8s-service
kubectl create clusterrolebinding entando-k8ssvc --clusterrole=cluster-admin --serviceaccount=entando-infra-namespace:default

# Create the resource from the file
kubectl create -f entando-infra.yaml -n entando-infra-namespace
----

[start=7]
. Create Entando App

*OpenShift*
----
# Create the project
oc new-project test-namespace

# Create the entando-app starting from the yaml
oc create -f entando-app.yaml -n test-namespace
----

*Kubernetes*
----
# Create the namespace
kubectl create namespace test-namespace

# Create the entando-app starting from the yaml
kubectl create -f entando-app.yaml -n test-namespace
----

== STEPS WITHOUT A CLUSTER ADMIN ROLE
* These instructions assume the target namespace/project is e6-namespace. If that's not your case, change the instructions accordingly *

[start=1]
. Manually install our Custom Resource Definitions:
Make a copy of the Entando CRD files that can be downloaded at:

[start=2]
. On a command line change to the resulting ./crd directory

[start=3]
. Temporary log in as a K8S cluster admin

[start=4]
. Execute this command:

----
oc create -f EntandoAppCRD.yaml -f EntandoAppPluginLinkCRD.yaml \
  -f  EntandoPluginCRD.yaml -f ExternalDatabaseCRD.yaml  \
  -f EntandoClusterInfrastructureCRD.yaml -f EntandoKeycloakServerCRD.yaml
----

[start=5]
. Grant cluster wide CRD read access only, and full access to Entando Custom resources. This requirement should not be a problem because there is no sensitive information in Entando’s custom resources.
----
oc create -f CRDAccessRole.yaml
oc adm policy add-cluster-role-to-user entando-operator system:serviceaccount:e6-namespace:default
----
Please heed all warnings from oc. There should be no warnings at this stage

[start=6]
. Create the operator deployment
Modify the operator.yaml file to reflect the two variables and modify the yaml accordingly

* ENTANDO_DEFAULT_ROUTING_SUFFIX *
* ENTANDO_K8S_OPERATOR_REGISTRY *

----
If you're using a local minikube instance, as value for ENTANDO_DEFAULT_ROUTING_SUFFIX use your minikube ip (or microk8s ip) + `.nip.io` suffix. With minikube, this command should return what you need echo "$(minikube ip).nip.io"
----

[start=7]
. Give namespace scoped admin rights to the default service-account:

----
oc policy add-role-to-user admin system:serviceaccount:e6-namespace:default
----

[start=8]
. Create the operator deployment:
----
oc create -f operator.yaml -n e6-namespace
----

[start=9]
. Setup keycloak
.. If you're using an external-keycloak instance.

Create external keycloak secret after updating the yaml file with the keycloak admin credentials

*OpenShift*
----
oc create -f keycloak-secret.yaml -n entando-controllers
----

*Kubernetes*
----
kubectl create -f keycloak-secret.yaml -n entando-controllers
----

.. If you need to create a local keycloak instance

Create a keycloak project

*OpenShift*
----
oc new-project keycloak-namespace
----

*Kubernetes*
----
kubectl create namespace keycloak-namespace
----

Create the keycloak resource

*OpenShift*
----
oc create -f keycloak-server.yaml -n keycloak-namespace
----

*Kubernetes*
----
kubectl create -f keycloak-server.yaml -n keycloak-namespace
----

Make sure the `keycloak-admin-secret` has been created in the entando-controllers namespace. If not, something went wrong during keycloak installation and you need to reinstall it

[start=10]
. Create Entando Cluster infrastructure (Digital Exchange, UserManagement and EntandoK8SService)

*OpenShift*
----
# Create the project
oc new-project entando-infra-namespace

# Add the cluster-admin role to the default service account on entando-infra-namespace, required for k8s-service
oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:entando-infra-namespace:default

# Create the resource from the file
oc create -f entando-infra.yaml -n entando-infra-namespace
----

*Kubernetes*
----
# Create the namespace
kubectl create namespace entando-infra-namespace

# Add the cluster-admin role to the default service account on entando-infra-namespace, required for k8s-service
kubectl create clusterrolebinding entando-k8ssvc --clusterrole=cluster-admin --serviceaccount=entando-infra-namespace:default

# Create the resource from the file
kubectl create -f entando-infra.yaml -n entando-infra-namespace
----

[start=11]
. Create Entando App

*OpenShift*
----
# Create the project
oc new-project test-namespace

# Create the entando-app starting from the yaml
oc create -f entando-app.yaml -n test-namespace
----

*Kubernetes*
----
# Create the namespace
kubectl create namespace test-namespace

# Create the entando-app starting from the yaml
kubectl create -f entando-app.yaml -n test-namespace
----

== AFTER INSTALLATION
