== Objective
The objective of this lab is to briefly introduce the Entand JHipster Blueprint and to provide an introduction to using the blueprint to generate a microservice and micro-frontends for deployment into an Entando application. 

== Prerequisites
* Java 1.8
* Maven 3.0.5+
* npm 6+
* git
* Docker
* node 10+ (or LTS)

== Setup for Blueprint Dev mode
1. Install JHipster
`npm install -g generator-jhipster`
+
2. Clone the entando blueprint  project to a location of your choice
`git clone https://github.com/entando/entando-blueprint`
3. On a command line enter the entando-blueprint directory just cloned and run this command
`npm link`
4. Create a new empty directory in a location of your choice outside of existing projects. 
Don't create this inside the entando-blueprint project
** This will be the directory where you create your plugin. 
** It is important that the commands below are run in the directory you are creating
5. On a command line change into the directory that you just created and run
`npm link generator-jhipster-entando`
6. Create a plugin using the blueprint. Run the following command
`jhipster --blueprints entando`
7. Select the following options (if nothing is specified in this list you can choose any available option
** Microservice application
** Name of application: training (Or whatever you want)
** Port: 8081
** Default package: com.entando (or whatever you want)
** SQL
** MySQL or Postgres
** H2 with disk based persistence
** Yes, with the Caffeine implementation
** 2nd level cache: Yes
** Maven
** Do not select any other technologies
** Accept the provided suggetion for the bundle name
** i18n: Yes
** Pick a default language
** Pick other languages you want
** Don’t add any other testing frameworks
** No other generators from the marketplace
8. Adding an Entity and Creating the Micro-Frontends. In your new project run the following command
`jhipster entity Conference`
** Select Yes for “Do you want to add a field to your entity”
** For the name of the field use: conferenceName
** Select String for type
** Select No for validation rules
** Select Yes for “Do you want to add a field to your entity”
** For the name of the field use: location
** Select String for type
** Select No for validation rules
** Select No for adding relationships
** Select No for Do you want to use separate service class for your business logic?
** You can choose any option you want here

Repeat the steps above for other entities that you want to add. Also, review the content and documentation around the JHipster Design Language (JDL) 
https://start.jhipster.tech/jdl-studio/

== Open the project in an IDE
This section just walks through the anatomy of the project and the Micro-frontends. You can skip this or review later as desired.
The top level project is a normal SpringBoot application. You can look through the code and configuration in src/main/java to get a view of the server side
The micro frontends are in the ui folder. Each entity gets an MFE for details, table, and form
