= PORTING FROM ENTANDO 5.0.0 TO 5.0.1

:sectnums:
:sectanchors:
:imagesdir: images/

Upgrading to Entando 5.0.1 requires you to complete two sets of steps.

== UPGRADE YOUR DATABASE

=== UPGRADE TO SPRING SECURITY AND REMOVE OLTU
. Execute the following queries: +
----
`-- ### DB *Serv ###

-- EN-1993
INSERT INTO api_oauth_consumers (consumerkey, consumersecret, name, description, callbackurl, scope, authorizedgranttypes, expirationdate, issueddate) VALUES ('appbuilder', '{bcrypt}$2a$10$axXuJXKHzgdmwQzBR3wvh.oSiiJp6On1pHxJgaBmwkRXnXqYqjhkK', 'Entando AppBuiler', 'Default Entando AppBuiler Consumer', NULL, 'read,write,trust', 'password,authorization_code,refresh_token,implicit', '2028-10-10 00:00:00', '2008-01-01 00:00:00');`
----

=== UPGRADE THE DATABASE FOR BPM/PAM PLUGIN
If you are using the _entando-plugin-jpkiebpm_, you need to add three columns to the _jpkiebpm_kieformoverride_ table (in db *serv), due to changes related to the task.

. In the Integrations > Components > Red Hat PAM Config, click the _Overrides List_ to open the Entando Error Page.
. Delete the old rows in the table or fill in appropriate values for the following columns: +
ALTER TABLE jpkiebpm_kieformoverride ADD COLUMN sourceid text; +
ALTER TABLE jpkiebpm_kieformoverride ADD COLUMN widgetinfoid integer; +
ALTER TABLE jpkiebpm_kieformoverride ADD COLUMN active boolean;
** widgetinfoid must be an id of the table _jpkiebpm_widgetinfo_
** sourceid must be an id of a configured BPM instance, defined inside _sysconfig_ table

== UPGRADE PROJECT CONFIGURATION

=== UPGRADE TO STRUTS 2.5.17
. Open the _src/main/conf_ and _src/main/conf/jboss_ directories. From each directory, open the _web.xml_ file and remove the listener class: +
_org.entando.entando.apsadmin.system.resource.EntandoPluginLabelListener_
. Open the _pom.xml_ and update the version of Struts2 into the properties section; from "2.5.10.1" to "2.5.17"

=== UPGRADE TO SPRING SECURITY AND REMOVE OLTU
. Open the _src/main/conf_ and _src/main/conf/jboss_ directories. From each directory, open the _web.xml_ file and remove the following:
** definition of "cors" filter and its filter-mapping
** definition of "AuthorizationServlet" and its servlet-mapping
** definition of "AccessTokenServlet" and its servlet-mapping
