= DIGITAL EXCHANGE

:sectnums:
:sectanchors:

Entando Digital Exchange is a marketplace from which users can install different Widgets, Components, Fragments, Page Models, Content Models and Content Types.

A Digital Exchange (DE) is a special Entando instance able to provide components that can be installed in other Entando instances via the App Builder.

== USING A DIGITAL EXCHANGE

In order to use a DE it is necessary to add the DE plugin to your Entando application adding the following dependency in the pom.xml file:

....
<dependency>
    <groupId>org.entando.entando.plugins</groupId>
    <artifactId>entando-plugin-jpdigital-exchange</artifactId>
    <version>${entando.version}</version>
    <type>war</type>
</dependency>
....

Then in the App Builder edit the .env file for enabling the DE

 DIGITAL_EXCHANGE_UI_ENABLED=true

Start you Entando instance and from the App Builder go to the Digital Exchange page (from top menu) and open the configuration panel (gear icon).

Click on "Add Digital Exchange" and configure the DE you want to use. You can also use multiple DE instances. Key and secret fields are used to connecting to the DE using OAuth2.
The DE administrator has to provide you this credentials.

You should now be able to see components provided by the DE and install them.

=== LOGGING/AUDITING INFORMATION

When an user starts an installation/uninstallation, the process is handled by an asynchronous job. Job information, including also start/end time, status and the user who triggered the job, is stored into the `digital_exchange_jobs` table (serv database).

== SETUP YOUR DIGITAL EXCHANGE

Clone or download the DE project: https://github.com/entando/digital-exchange and start it in the same way of other Entando instances.

=== CREATE CREDENTIALS FOR DIGITAL EXCHANGE CLIENTS

From the Admin Console go to Integrations > API Management > *Consumers*

Add a new Consumer:

. fill the required fields
.. Callback URL is blank
.. scope is "read,write,trust"
. in "Authorized Grant Types" section, set to ON the `client_credentials` toggle button.

This credentials have to be put by DE clients inside their DE configuration (see above).

=== CREATE A COMPONENT

A component consists in a folder containing a set of files that are used to insert new data into an Entando instance.
Component providers need to create these files carefully respecting the constraints listed below. To generate the structure of simple components like a page model we suggest using the dedicated command of the command line tool (see section "custom local components").

A component has a name, a version and an id. The id must be unique between all the exchanges, so it can be a composition of a DE unique identifier, the component name and the component version.

Inside the component folder it is mandatory to have a file named *component.xml* (the component descriptor), describing the component installation/uninstallation needs.
The component descriptor can reference other files using a relative path, so all the paths must be prefixed by the component id (e.g. `<component_id>/relative/path`).

Other files must be put in the following sub-directories:

. *data*: used for files needed only during the installation/uninstallation process;
. *resources*: used for public resources (like images, CSS and JavaScript files).

==== DEFINE INSTALLATION/UNINSTALLATION OPERATIONS

The component descriptor can contain a sequence of operations defined using Spring SpEL: this allows the execution of bean methods.

....
<component>
    <!-- ... -->
    <installation>
        <execution>
            <op>@myBean.myMethod()</op>
            <op>...</op>
        </execution>
    </installation>
</component>
....

The most common use case is to call a controller method, which usually needs a model passed as parameter. The model can be parsed from a JSON or XML file.
It is possible to use a simple bean called `ModelParser` to do this inside a SpEL expression, e.g.:

 @modelParser.parse('<component_id>/data/my_model.json', T(org.entando.entando.web.MyModelClass))

The system provides also some *utility functions* in order to simplify the writing of the most common operations:

. the `#bindingResult()` custom SpEL function provides an instance of a `BindingResult` class, used in a lot of controllers for handling validation error messages;
. the `#call()` custom SpEL function can be used for the most common operations, like creating a label or a contentModel. It accepts an operation name as the first parameter and the path of a file containing the model for that operation as the second parameter. So, for example, for creating a label it is possible to use the following expression: `#call('createLabel', '<component_id>/data/label.json')`

- Supported operations are:

.. `createPageModel`/`deletePageModel`
.. `createWidget`/`deleteWidget`
.. `createGroup`/`deleteGroup`
.. `createRole`/`deleteRole`
.. `createLabel`/`deleteLabel`
.. `createContentType`/`deleteContentType` (CMS plugin must be installed)
.. `createContentModel`/`deleteContentModel` (CMS plugin must be installed)

==== USE STATIC RESOURCES IN A PAGE MODEL

If you put a static resource in the resources folder, after the installation it will be available at the following URL:

 <resources_url>/components/<component_id>/<resource_name>

So you can reference it from a FreeMarker template using the dedicated tag:

....
<#assign wp=JspTaglibs["/aps-core"]>
    <!-- ... ->
    <@wp.resourceURL />components/my_component_id/style.css" />
....

==== SQL EXECUTION

Even if it is discouraged (because it ignores validation logic), it is possible to execute SQL statements during the installation/uninstallation process.

Put your SQL file into the data directory and reference it in the component.xml, specifying if its target is the port or the serv database, as in the following example:

....
<component>
    <!-- ... -->
    <installation>
        <environment code="production">
            <defaultSqlResources>
                <datasource name="portDataSource">
                    my_component_id/data/scriptPort.sql
                </datasource>
                <datasource name="servDataSource">
                    my_component_id/data/scriptServ.sql
                </datasource>
            </defaultSqlResources>
        </environment>
    </installation>
</component>
....

==== EXAMPLES

Some complete examples can be found here: https://github.com/entando/de-cli/tree/master/demo_components/data

You can upload these demo components on your DE using the DE command line tool (see section below).

=== CONFIGURE THE DE TO PROVIDE A COMPONENT

Put your component folder on a git repository and then configure the DE to retrieve component data from that repository. A graphical interface for doing this has not been implemented yet, but we have implemented a command line tool that calls directly the DE API.

You can get the tool at this repository: https://github.com/entando/de-cli

Follow the instructions provided in the README for installing the tool (npm and node are required).

Type `./de-cli.js --help` to see the list of the supported components.

==== SETUP THE KEYPAIR

Each component package is signed after its creation using asymmetric cryptography, in order to prevent clients to install tampered packages.

So, before adding any component metadata, it is necessary to create a keypair. This can be done using the following command:

....
./de-cli.js create-keypair
....

The private key is stored on disk and it is encrypted using the password set in the .env file (see `DE_COMPONENT_PASSWORD` property).

If you want to verify the keypair existence you can obtain the public key using the following command:

....
./de-cli.js print-public-key
....

If you need to delete the keypair you can use the following command:

....
./de-cli.js delete-keypair
....

When a keypair is deleted all the component package signatures are set to null (so it is not possible to install the components). Signatures are generated again when a new keypair is created. *WARNING*: If you generate a new keypair you have to notify all your clients that the keypair is changed. A DE client retrieves the public key from the DE when its configuration is added, so clients need to delete their DE configuration and add it again in order to retrieve the updated public key.

==== ADD REPOSITORY INFORMATION

DE components are retrieved from one or more git repositories. Add the repository configuration using the `add-repository` command and typing the asked information:

....
./de-cli.js add-repository
Repository name: demo_repo
Repository URL: https://github.com/entando/de-cli.git
....

An unique identifier is generated for each repository and it is used for referencing the repository in other commands. Currently only public repositories are supported.

To obtain the list of all configured repositories you can use:

....
./de-cli.js list-repositories
....

To delete a repository you can use:

....
./de-cli.js delete-repository <repo-id>
....

==== ADD COMPONENT METADATA

After you have added a repository you can add component metadata in order to create a package.

There are 2 ways to add component metadata: interactively and from a JSON file.

The interactive mode asks you the component metadata (a list of available repository identifiers is provided):

....
./de-cli.js add-component
Component name: hello_widget
Component version: 5.2.0-V1
Component id (hello_widget_5.2.0-V1): hello_widget_v1
Component description: Hello Widget Description
Component type: widget
Repository id
[Available 503 (demo_repo)]: 503
Repository directory: demo_components/data/hello_widget
Commit id (empty for last commit):
Component hello_widget_v1 added
....

The metadata can contain also a commit id (useful for supporting multiple versions of the same component) and a repository subdirectory (useful for providing multiple components using a single repository).

Alternatively you can create a JSON file containing this information and pass it to the command:

....
{
    "id": "hello_widget_v1",
    "name": "hello_widget",
    "description": "Hello Widget Description",
    "type": "widget",
    "version": "5.2.0-V1",
    "repoId": 503,
    "repoDirectory": "demo_components/data/hello_widget"
}

./de-cli.js add-component hello_widget.json
....

The insertion of a component metadata triggers the retrieval of the component data from the configured git repository. The data is packed as a zip file and the signature of this package is generated. This process happens asynchronously, so it could take some time before the signature is initialized. You can use the command `list-components` to check the existence of the signature (a component without a signature can't be installed):

....
./de-cli.js list-components
┌─────────┬───────────────────┬──────────┬───────────┐
│ (index) │        id         │   type   │ signature │
├─────────┼───────────────────┼──────────┼───────────┤
│    0    │ 'hello_widget_v1' │ 'widget' │   'YES'   │
└─────────┴───────────────────┴──────────┴───────────┘
....

To delete a component use:

....
./de-cli.js delete-component <component_id>
....

==== UPLOAD COMPONENT IMAGE

....
./de-cli.js add-component-image <component_id> <file>
....

==== DEMO COMPONENTS

The DE command line tool repository provides also a folder containing a set of demo components.
To add all these components and their icons use:

....
./de-cli.js add-demo-components
....

Keypair and demo repository are automatically added if they are missing.

To delete the demo components and the demo repository use:

....
./de-cli.js cleanup-demo-components
....

==== CUSTOM LOCAL COMPONENTS

If you want to create your first custom components and test them locally you can use the dedicated command that guides you in the creation using some templates.
The command line tools will generate a folder for the component inside the directory specified in the .env file using the property `LOCAL_REPO_URL`. This folder must be outside the de-cli repository because it is versioned using git too.

....
./de-cli.js create-local-component
Select component type:
1. contentModel
2. contentType
3. pageModel
4. widget
Component type: 1
Component name: my_content_model
Component version: 1.0
Component id (my_content_model_1.0):
Component description: My description
....

This will generate a basic component in your local repository directory. Changes are automatically committed to the git repository after the component generation. If you want to customize the generated component remember to commit your additional changes.

You can add the generated component to the DE using the `add-component` command, but for the local components we provide also a simplified version that needs only the component id:

....
./de-cli.js add-local-component <component-id>
....

If you want to delete a component both from the DE and the local repository you can use the following command:

....
./de-cli.js delete-local-component <component-id>
....

We suggest using this command instead of a manual removal because it automatically commits the removed directory and cleanups the component metadata on the DE.

=== CUSTOMIZE COMPONENT RATING

Component rating functionality can be customized editing the file src/main/resources/digital-exchange.properties:

To completely disable the rating service use:

....
enable-rating=false
....

If you need to change the range of the stored rating values you can update the limits using the following properties:

....
rate-min=0
rate-max=10
....

This can be useful in order to provide compatibility with other rating system. Notice that the range is adapted only inside the database, while the API will always work using the 1-5 range to adopt a standardized range between all the DE instances. This corresponds to the stars on the UI.

So, using the range provided in the example the conversion will be:

[width="50%",options="header"]
|=======
|API value |DB value
|1 |0
|2 |2.5
|3 |5
|4 |7.5
|5 |10
|=======

== TROUBLESHOOTING

=== Client issues

==== Invalid signature

As a security measure all the component packages are signed. If, installing a component, the installation job fails with the error "_SignatureMatchingException: Component signature not matching public key_", it means that signature verification has failed. This can have 2 different causes:

. the package has been tampered, so the system avoided you to install a broken/malicious package;
. the DE administrator regenerated the keypair used in the signature.

So, ask to the DE administrator if he/she has just regenerated the keypair and in that case delete the DE configuration and add it again. This will trigger the retrieval of the new public key from the DE.
