= Tutorial: How to connect Entando 6 to an external keycloak instance
:toc:

== Purpose
Purpose of this tutorial is to enable the Entando6 maintainer to reuse an 
existing Keycloak instance

== Requirements
- A reachable Keycloak instance
- A realm named "Entando" on that instance
- An admin user for the Entando realm 

== Steps

=== 1. Get keycloak informations
First you need to get the relevant information from the keycloak you want to use. 

Specifically you will need:

- The keycloak url including the auth value, e.g. https://my-keycloak-instance.com/auth
- The keycloak admim username, e.g entando-keycloak-admin
- The keycloak admin password, e.g. password123

=== 2. Generate the secret

You now need to generate a secret with name _keycloak-admin-secret_ using the information retrieved from step 1.

Here is an example of the secret you will need to write/generate
```
---
apiVersion: v1
data:
    password: <your-password-encoded-in-base64>
    url: <your-url-encoded-in-base64>
    username: <your-username-encoded-in-base64>
kind: Secret
metadata
    name: keycloak-admin-secret
    namespace: <your-app-namespace>
type: Opaque
```

=== 3. Upload the secret
Now you only need to upload the secret to the namespace where you want to deploy your Entando 6 instance. 

```
oc create -f my-secret.yaml -n <my-app-namespace>
```

=== 4. Deploy the Entando6 application
Now you are ready to deploy your Entando6 application and the operator will reuse the _keycloak-admin-secret_ secret to populate the environment correctly

== Conclusion
You should have now a working Entando6 instance using an external keycloak