[id='docker']
:sectnums:
:imagesdir: ../images

= RUNNING ENTANDO WITH DOCKER  

*Full Stack Example Images*

The project below includes scripts and example images that will boot up a full stack of Entando apps in Docker.
https://github.com/entando/entando-ops/tree/master/Docker/Production/entando-full-stack

These projects are useful to quickly boot up an Entando environment in Docker.
Can be forked/cloned for extension and updates as needed as well. Scripts and image names
can be seen in the repository

*Base Image*

This base image provides a base Dockerfile that can be extended to create and manage an Entando application.
The base image downloads all of the maven dependencies required for an application to run so the initial run can take some time however
after that edits to a child Dockerfile will run fast. The base example in the Readme uses a jetty/derby combination for execution

https://github.com/entando/entando-ops/tree/master/Docker/Production/builder-images/docker-builder-5

*Using S2I to Build Docker Images*

To use the Docker S2I images, you must have already set up a database. See the Setting up a Database section for details.

By default, the app deployed in Docker will connect to a Postgres database to persist resources created using the App Builder and by the MApp Engine.
In the app created from the archetype, update the properties in:
*<your application>/.s2i/environment* to point to the user and databases created in the Setting up a Database section.

*After configuring the database:*

. Pull in the Docker image using the following command: +
`+docker pull entando/builder-s2i+` (Demo image using Jetty)

. Build the image using S2I using the command to build and deploy a Docker app in Docker: +
`+s2i build <path or URL of your project> entando/builder-s2i <your  image name>+` +
*Where:* +
* *<path or URL of your project>* is the path to your project or a URL to access the code. The build for this project will be invoked and the resulting war file deployed to the app server in the image
* *entando/builder-s2i* is the name of the base S2I docker image provided by Entando
* *<your image name>* is the name for this docker image

*Run the Image*

`docker run -d -p 8080:8080 <your image name>`

The app may take some time to start. It is downloading maven dependencies at startup.
Your app will be available on http://localhost:8080/<your_project_name> after startup is complete.

By default the image exposes port 8080 however you can change the local port mapped to that value
by editing the first instance of 8080 in the docker run command above.
