= Tutorial: Connecting to an External Database
:toc:

== Overview
This document provides a guide to connecting to an external database. In many (not all) production configurations
it is recommended to use a DBMS outside of the cluster where your Entando applicaiton is running to simplify
maintenance, duplication of resources, and to establish a backup workflow that will scale with your application.

== Prerequisites
* An environment to install your Entando applicaiton
* A running PostgreSQL, MySQL, or Oracle environment
* Administrator access to the database
* Network access from your Kubernetes cluster to your database

== Tutorial

. In the helm quickstart in `values.yaml` define a db for your deployment that includes the admin credentials for your database

```
db:
  vendor: postgresql | mysql | oracle
  host: <yourhost>
  port: <yourport>
  adminUser: <youradmin>
  adminPassword: <youradminpassword>
  name: <yourdbname>
```

. In the helm quickstart in the `templates` folder make a backup copy of your current `entando-composite-app.yaml` and
move the file `entando-composite-app.yaml.external.db` to  `entando-composite-app.yaml`
.. FYI -- The external db config for the `entando-composite-app` has the following changes if you want to apply the manually
... Change all `dbms` entries to `{{ .Values.db.vendor }}`
... Adds an EntandoDatabaseService CRD to the composite app (this tells the operator to use the secret and provided connection)
... Adds a top level Secret for the database
. Run the helm quickstart or create a deployment for your Entando environment manually
.. Note: The quickstart creates a default configuration for the deployment. This isn't to suggest that it is the only
configuration or that it matches with every use case. It is recommended to think about your desired deployment Architecture
and to configure for that environment using the CRDs as building blocks. This also isn't to suggest that if it isn't directly supported by the quickstart template that you
can't change it. The deployment is editable. Treat the helm template as a bootstrapping environment and edit your deployments to match your needs and requirements.
. Open the yaml file generated from the deployment and review the settings for the deployment
.. The Entando Operator will create a secret for the database automatically and use the DB initializers to create the DB for the Entando app and any services that use it
. Deploy your app
