[id='rh-getting-started']

:sectnums:
:imagesdir: images/

= GETTING STARTED WITH ENTANDO AND PAM

== Overview
This document provides an introduction to using the Entando App Builder integrated with Red Hat Process Application Manager. This template application provides a page with a task list, task details, case comments (optional), and case management widgets (optional). The provided application can then be extended and customized using the App Builder functionality.

=== Launch the Template Application
Unzip the provided project (entando-pam-app-5.0.3.zip)

. On a command line cd into the application (for example cd entando-pam-demo-app)
. Start the project with this command:

`mvn jetty:run -Djetty.reload=manual -Djetty.port=8083 -Dspring.profiles.active=swagger`

.. Notes on this command and the environment
... *mvn jetty:run* --  Run in jetty for quick start and development
... *jetty.reload=manual* -- to prevent jetty from reloading changes in your project
... *-Djetty.port=8083*  -- Change the default port to 8083. Without this jetty will start on 8080 and usually conflict with something else in the environment
... *-Dspring.profiles.active=swagger* -- Enable swagger on the project so we can look at the APIs and API documentation. Disabled by default. This can also be exported as an environment variable: export spring_profiles_active=swagger
. Wait for the project to start. Look for: Started Jetty Server.  Console Reloading is Enabled
. In a browser navigate to: http://localhost:8083/entando-pam-app-5.0.3

=== Add the KIE server configuration
. Navigate to  http://localhost:8083/entando-pam-app-5.0.3/do/login
. Login with
.. User: admin
.. Password: adminadmin
. On the left pane select Integrations → Components → Red Hat PAM Config
. In the upper right select Add Configuration
... Name - Enter the name of your choice for the configuration
... Hostname - The host where your KIE server is running. For example (localhost). Do not include http:// or ports
... Schema: One of http or https depending on where your KIE server is running
... Port - Enter the port of the http interface of your KIE server. If any. Can be left blank. For example 8080 is common if KIE is running locally
... WebApp Name - The value that comes after the port in your KIE URL. If any. Can be left blank. A common value is kie-server when running KIE locally
... Username - PAM Admin username. Common value is pamAdmin
... Password - The password for the KIE user
... Conn. Timeout (in millis) - Millisecond timeout for connecting to KIE. Can be blank
. Hit Test connection and you’ll get a green banner if the connection is valid
. Select Save _(don’t forget this)_

=== - Configure the Widgets to Use your PAM Connection
The demo app comes with a collection of widgets pre-applied in the pages but they need to be configured to use the new KIE configuration created in Part 2 above.

. In the left nave select Page Designer → Page Tree
. In the page tree in the kebab menu on the right select the menu for the page named Task List
. Select Configure
. On this page the widget in the middle of the screen called PAM-Datatable Task List holds the task list for our application. Select the kebab menu on the right and select settings
. On this page fill out the configuration for you new PAM instance
.. Knowledge Source - this will be the name of the PAM integration you selected and configured above
.. Process - The process you want to fetch tasks for
.. Open new page on table row click - Select ON
.. Show Claim button - Select ON
.. Show Complete Button  - Select ON
.. Under BPM Groups - Select ON for all of the provided groups
 ... Note: If modeling a process with different groups you need to add those groups to Entando under the left menu Setting → Groups and enter the names to match exactly the groups used in PAM
.. Override Fields
... These are the columns that will show up in your table. They are fetched from Task and Process variables. You can provide a different column header under Override fields and remove columns using the check boxes
. Select Save at the bottom of the screen
. Hit the green Publish button at the top of the page
. In the upper right select Pages
. On the row that says task-details click on the row and then on the right and select the kebab button
. Select configure
. Select the kebab button on the widget labeled PAM-Task Form by Data Type
. Select settings
. Select the Knowledge Source and Process
. Click Save
. Click the green publish button
. Optional step
.. If the application you are building is using Case Management functionality you can also add the PAM Case Comments widget to the box labeled Widget 4 by searching for the widget on the right and dragging it to the page. Then configure that widget with the Knowledge Source and Process
.. Click Save and Publish

== Update the Home Screen of your Application
. On the left menu select Page Designer → Page Settings
. In the top dropdown labeled Home page* select ../Task List
. Select Save

== View your Application
. In the upper right of the application select Go to Homepage
. If there are human tasks available in your PAM process for the roles assigned to your PAM user they will show up in the table
. Clicking on a row in the table will take you to the task details page in a new tab
