name: Entando Docs
on:
  push:
  workflow_dispatch:
env:
  DOCS_DIR: vuepress
jobs:
  run-check-md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: vuepress/yarn.lock
      - run: |
          cd $GITHUB_WORKSPACE/$DOCS_DIR
          yarn install
          yarn docs:check-md
